_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    methods: GET|HEAD
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'

login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::login
    requirements:
        _locale: '%app_locales%'

logout:
    path: /{_locale}/logout
    controller: App\Controller\SecurityController::logout
    requirements:
        _locale: '%app_locales%'

register:
    path: /{_locale}/register
    controller: App\Controller\RegistrationController::register
    requirements:
        _locale: '%app_locales%'

verify_email:
    path: /{_locale}/verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    requirements:
        _locale: '%app_locales%'

user_index:
    path: /{_locale}/users/{page}
    controller: App\Controller\UserController::index
    methods: GET|HEAD|POST
    defaults:
        page: 1
    requirements:
        _locale: '%app_locales%'
        page: '\d+'

user_show:
    path: /{_locale}/user/{id}/{name}
    controller: App\Controller\UserController::show
    methods: GET|HEAD|POST
    requirements:
        id: '\d+'
        _locale: '%app_locales%'

user_edit:
    path: /{_locale}/user/{id}/{name}/edit
    controller: App\Controller\UserController::edit
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

user_delete:
    path: /{_locale}/user/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

user_posts:
    path: /{_locale}/user/{id}/{name}/posts/{page}
    controller: App\Controller\UserController::showPosts
    methods: GET|HEAD
    defaults:
        page: 1
    requirements:
        id: '\d+'
        page: '\d+'
        _locale: '%app_locales%'

user_favorites:
    path: /{_locale}/user/{id}/{name}/favorites/{page}
    controller: App\Controller\UserController::showFavorites
    methods: GET|HEAD|POST
    defaults:
        page: 1
    requirements:
        id: '\d+'
        page: '\d+'
        _locale: '%app_locales%'

user_favorites_edit:
    path: /{_locale}/user/{id}/{name}/favorites/edit
    controller: App\Controller\UserController::editFavorites
    methods: GET|HEAD|POST
    format: 'json'
    defaults:
        page: 1
    requirements:
        id: '\d+'
        page: '\d+'
        _locale: '%app_locales%'

user_likes:
    path: /{_locale}/user/{id}/{name}/likes/{page}
    controller: App\Controller\UserController::showLikes
    methods: GET|HEAD|POST
    defaults:
        page: 1
    requirements:
        id: '\d+'
        page: '\d+'
        _locale: '%app_locales%'

user_likes_edit:
    path: /{_locale}/user/{id}/{name}/likes/edit
    controller: App\Controller\UserController::editLikes
    methods: GET|HEAD|POST
    format: 'json'
    defaults:
        page: 1
    requirements:
        id: '\d+'
        page: '\d+'
        _locale: '%app_locales%'

post_index:
    path: /{_locale}/posts/{page}
    controller: App\Controller\PostController::index
    methods: GET|HEAD
    defaults:
        page: 1
    requirements:
        _locale: '%app_locales%'
        page: '\d+'

post_show:
    path: /{_locale}/post/{id}/{slug}
    controller: App\Controller\PostController::show
    methods: GET|HEAD
    requirements:
        id: '\d+'
        _locale: '%app_locales%'

post_edit:
    path: /{_locale}/post/{id}/edit
    controller: App\Controller\PostController::edit
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

post_delete:
    path: /{_locale}/post/{id}
    controller: App\Controller\PostController::delete
    methods: DELETE
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

post_new:
    path: /{_locale}/post/new
    controller: App\Controller\PostController::new
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'