_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

homepage:
    path: /{_locale}
    controller: App\Controller\PostController::index
    methods: GET|HEAD
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

app_login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::login
    requirements:
        _locale: '%app_locales%'

app_logout:
    path: /{_locale}/logout
    controller: App\Controller\SecurityController::logout
    requirements:
        _locale: '%app_locales%'

app_register:
    path: /{_locale}/register
    controller: App\Controller\RegistrationController::register
    requirements:
        _locale: '%app_locales%'

app_verify_email:
    path: /{_locale}/verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    requirements:
        _locale: '%app_locales%'

user_index:
    path: /{_locale}/user
    controller: App\Controller\UserController::index
    methods: GET|HEAD
    requirements:
        _locale: '%app_locales%'

user_show:
    path: /{_locale}/user/{id}
    controller: App\Controller\UserController::show
    methods: GET|HEAD
    requirements:
        id: '\d+'
        _locale: '%app_locales%'

user_edit:
    path: /{_locale}/user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

user_delete:
    path: /{_locale}/user/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

post_index:
    path: /{_locale}/post/
    controller: App\Controller\PostController::index
    methods: GET|HEAD
    requirements:
        _locale: '%app_locales%'

post_show:
    path: /{_locale}/post/{id}
    controller: App\Controller\PostController::show
    methods: GET|HEAD
    requirements:
        id: '\d+'
        _locale: '%app_locales%'

post_edit:
    path: /{_locale}/post/{id}/edit
    controller: App\Controller\PostController::edit
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

post_delete:
    path: /{_locale}/post/{id}
    controller: App\Controller\PostController::delete
    methods: DELETE
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

post_new:
    path: /{_locale}/post/new
    controller: App\Controller\PostController::new
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'