_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    methods: GET|HEAD
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'

login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::login
    requirements:
        _locale: '%app_locales%'

logout:
    path: /{_locale}/logout
    controller: App\Controller\SecurityController::logout
    requirements:
        _locale: '%app_locales%'

register:
    path: /{_locale}/register
    controller: App\Controller\RegistrationController::register
    requirements:
        _locale: '%app_locales%'

verify_email:
    path: /{_locale}/verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    requirements:
        _locale: '%app_locales%'

user_index:
    path: /{_locale}/users/{page}
    controller: App\Controller\UserController::index
    methods: GET|HEAD|POST
    requirements:
        _locale: '%app_locales%'
        page: '\d+'
    defaults:
        page: 1

user_show:
    path: /{_locale}/user/{id}
    controller: App\Controller\UserController::show
    methods: GET|HEAD|POST
    requirements:
        id: '\d+'
        _locale: '%app_locales%'

my_profile:
    path: /{_locale}/me/profile
    controller: App\Controller\UserController::show
    methods: GET|HEAD|POST
    requirements:
        _locale: '%app_locales%'
    defaults:
        id: null

user_edit:
    path: /{_locale}/user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

my_profile_edit:
    path: /{_locale}/me/profile/edit
    controller: App\Controller\UserController::edit
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
    defaults:
        id: null

user_delete:
    path: /{_locale}/user/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

user_posts:
    path: /{_locale}/user/{id}/posts/{page}
    controller: App\Controller\UserController::showPosts
    methods: GET|HEAD
    requirements:
        _locale: '%app_locales%'
        id: '\d+'
        page: '\d+'
    defaults:
        page: 1

my_posts:
    path: /{_locale}/me/posts/{page}
    controller: App\Controller\UserController::showPosts
    methods: GET|HEAD
    requirements:
        _locale: '%app_locales%'
        page: '\d+'
    defaults:
        page: 1
        id: null

user_image_new:
    path: /{_locale}/user/{id}/image/new
    controller: App\Controller\ImageController::new
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

my_image_new:
    path: /{_locale}/me/image/new
    controller: App\Controller\ImageController::new
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
    defaults:
        id: null

image_delete:
    path: /{_locale}/user/{id}/image/{image}/delete
    controller: App\Controller\ImageController::delete
    methods: DELETE
    requirements:
        _locale: '%app_locales%'
        id: '\d+'
        image: '\d+'

image_move:
    path: /{_locale}/user/{id}/image/{image}/move/{dir}
    controller: App\Controller\ImageController::move
    methods: GET
    requirements:
        _locale: '%app_locales%'
        id: '\d+'
        image: '\d+'
        dir: up|down

image_main:
    path: /{_locale}/user/{id}/image/{image}/main
    controller: App\Controller\ImageController::main
    methods: GET
    requirements:
        _locale: '%app_locales%'
        id: '\d+'
        image: '\d+'

image_background:
    path: /{_locale}/user/{id}/image/{image}/background
    controller: App\Controller\ImageController::background
    methods: GET
    requirements:
        _locale: '%app_locales%'
        id: '\d+'
        image: '\d+'

user_favorites:
    path: /{_locale}/user/{id}/favorites/{page}
    controller: App\Controller\FavoriteController::index
    methods: GET|HEAD|POST
    requirements:
        _locale: '%app_locales%'
        id: '\d+'
        page: '\d+'
    defaults:
        page: 1
        id: null

my_favorites:
    path: /{_locale}/me/favorites/{page}
    controller: App\Controller\FavoriteController::index
    methods: GET|HEAD|POST
    requirements:
        _locale: '%app_locales%'
        page: '\d+'
    defaults:
        page: 1
        id: null

user_favorite_new:
    path: /{_locale}/favorite/{favorite}/new
    controller: App\Controller\FavoriteController::new
    methods: GET|POST
    format: 'json'
    requirements:
        _locale: '%app_locales%'
        favorite: '\d+'

user_favorite_delete:
    path: /{_locale}/favorite/{favorite}/delete
    controller: App\Controller\FavoriteController::delete
    methods: DELETE
    format: 'json'
    requirements:
        _locale: '%app_locales%'
        favorite: '\d+'

user_likes:
    path: /{_locale}/user/{id}/likes/{page}
    controller: App\Controller\LikeController::index
    methods: GET|HEAD|POST
    requirements:
        id: '\d+'
        page: '\d+'
        _locale: '%app_locales%'
    defaults:
        page: 1

my_likes:
    path: /{_locale}/me/likes/{page}
    controller: App\Controller\LikeController::index
    methods: GET|HEAD|POST
    requirements:
        _locale: '%app_locales%'
        page: '\d+'
    defaults:
        page: 1
        id: null

user_like_new:
    path: /{_locale}/like/{like}/new
    controller: App\Controller\LikeController::new
    methods: GET|POST
    format: 'json'
    requirements:
        _locale: '%app_locales%'
        like: '\d+'

user_like_delete:
    path: /{_locale}/like/{like}/delete
    controller: App\Controller\LikeController::delete
    methods: DELETE
    format: 'json'
    requirements:
        _locale: '%app_locales%'
        like: '\d+'

my_friends:
    path: /{_locale}/me/friends/{page}
    controller: App\Controller\FriendController::index
    methods: GET|HEAD|POST
    requirements:
        _locale: '%app_locales%'
        page: '\d+'
    defaults:
        page: 1
        id: null

user_friend_new:
    path: /{_locale}/friend/{friend}/new
    controller: App\Controller\FriendController::new
    methods: GET|POST
    format: 'json'
    requirements:
        _locale: '%app_locales%'
        friend: '\d+'

post_index:
    path: /{_locale}/posts/{page}
    controller: App\Controller\PostController::index
    methods: GET|HEAD
    requirements:
        _locale: '%app_locales%'
        page: '\d+'
    defaults:
        page: 1

post_show:
    path: /{_locale}/post/{id}
    controller: App\Controller\PostController::show
    methods: GET|HEAD
    requirements:
        id: '\d+'
        _locale: '%app_locales%'

post_edit:
    path: /{_locale}/post/{id}/edit
    controller: App\Controller\PostController::edit
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

post_delete:
    path: /{_locale}/post/{id}
    controller: App\Controller\PostController::delete
    methods: DELETE
    requirements:
        _locale: '%app_locales%'
        id: '\d+'

post_new:
    path: /{_locale}/post/new
    controller: App\Controller\PostController::new
    methods: GET|POST
    requirements:
        _locale: '%app_locales%'