homepage:
    path: /
    controller: App\Controller\UserController::index

app_login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::login
    requirements:
        _locale: en|de|fr

app_logout:
    path: /{_locale}/logout
    controller: App\Controller\SecurityController::logout
    requirements:
        _locale: en|de|fr

app_register:
    path: /{_locale}/register
    controller: App\Controller\RegistrationController::register
    requirements:
        _locale: en|de|fr

app_verify_email:
    path: /{_locale}/verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    requirements:
        _locale: en|de|fr

user_index:
    path: /{_locale}/user
    controller: App\Controller\UserController::index
    requirements:
        _locale: en|de|fr

user_show:
    path: /{_locale}/user/{id}
    controller: App\Controller\UserController::show
    methods: GET|HEAD
    requirements:
        id: '\d+'
        _locale: en|de|fr

user_edit:
    path: /{_locale}/user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: GET|POST
    requirements:
        _locale: en|de|fr
        id: '\d+'

user_delete:
    path: /{_locale}/user/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE
    requirements:
        _locale: en|de|fr
        id: '\d+'